<script type="text/javascript">
<!-- 
document.writeln(" <!DOCTYPE html> "); 
document.writeln(" <html> "); 
document.writeln(" <head> "); 
document.writeln(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> "); 
document.writeln(" <style> "); 
document.writeln(" * { "); 
document.writeln("   box-sizing: border-box; "); 
document.writeln(" } "); 
document.writeln("  "); 
document.writeln(" body { "); 
document.writeln("   margin: 0; "); 
document.writeln("   font-family: Arial; "); 
document.writeln("   font-size: 17px; "); 
document.writeln(" } "); 
document.writeln("  "); 
document.writeln(" #myVideo { "); 
document.writeln("   position: fixed; "); 
document.writeln("   right: 0; "); 
document.writeln("   bottom: 0; "); 
document.writeln("   min-width: 100%;  "); 
document.writeln("   min-height: 100%; "); 
document.writeln(" } "); 
document.writeln("  "); 
document.writeln(" .content { "); 
document.writeln("   position: fixed; "); 
document.writeln("   bottom: 0; "); 
document.writeln("   background: rgba(0, 0, 0, 0.5); "); 
document.writeln("   color: #f1f1f1; "); 
document.writeln("   width: 100%; "); 
document.writeln("   padding: 20px; "); 
document.writeln(" } "); 
document.writeln("  "); 
document.writeln(" #myBtn { "); 
document.writeln("   width: 200px; "); 
document.writeln("   font-size: 18px; "); 
document.writeln("   padding: 10px; "); 
document.writeln("   border: none; "); 
document.writeln("   background: #000; "); 
document.writeln("   color: #fff; "); 
document.writeln("   cursor: pointer; "); 
document.writeln(" } "); 
document.writeln("  "); 
document.writeln(" #myBtn:hover { "); 
document.writeln("   background: #ddd; "); 
document.writeln("   color: black; "); 
document.writeln(" } "); 
document.writeln(" .button { "); 
document.writeln("   background-color: #A0522D; /* Green */ "); 
document.writeln("   border: none; "); 
document.writeln("   color: white; "); 
document.writeln("   padding: 15px 32px; "); 
document.writeln("   text-align: center; "); 
document.writeln("   text-decoration: none; "); 
document.writeln("   display: inline-block; "); 
document.writeln("   font-size: 16px; "); 
document.writeln(" } "); 
document.writeln(" </style> "); 
document.writeln(" </head> "); 
document.writeln(" <body> "); 
document.writeln("  "); 
document.writeln(" <video autoplay muted loop id=\"myVideo\"> "); 
document.writeln("   <source src=\"abc.mp4\" type=\"video/mp4\"> "); 
document.writeln(" </video> "); 
document.writeln(" <div class=\"content\"><div> "); 
document.writeln("     <div></div> "); 
document.writeln("      <div><center><h2>STAFFS</h2></center> </div> "); 
document.writeln(" <center> "); 
document.writeln("  <h3> Name: "); 
document.writeln("   <input type=\"text\" name=\"name\"><br><br> "); 
document.writeln("   Adhaar number: "); 
document.writeln(" <input type=\"text\" name=\"adhar\" required pattern=\"[0-9]{4} [0-9]{4} [0-9]{4}\"> <span class=\"validity\"></span><br> "); 
document.writeln("   <br> "); 
document.writeln("   Staff Idenity Number: "); 
document.writeln("   <input type=\"text\" name=\"sid\"><br> "); 
document.writeln("   <br> "); 
document.writeln("   Home Identity Number: "); 
document.writeln("   <select name=\"h_id\"> "); 
document.writeln("     <option value=\"1\">Home1</option> "); 
document.writeln("     <option value=\"2\">Home2</option> "); 
document.writeln("     <option value=\"3\">Home3</option> "); 
document.writeln("       </select> "); 
document.writeln("   <br><br> "); 
document.writeln("  Address:<textarea></textarea><br> "); 
document.writeln("  <br> "); 
document.writeln("  Salary: <input type=\"text\" name=\"salary\"></br> "); 
document.writeln("  <br> "); 
document.writeln("   Phone Number: "); 
document.writeln("  <input type=\"text\" name=\"phone_no\"required pattern=\"[0-9]{5} [0-9]{5}\"> <span class=\"validity\"></span></br> "); 
document.writeln("  "); 
document.writeln("     </br> "); 
document.writeln("   </br><button type =\"submit\" class=\"button\"value=\"\">Submit</button></br> "); 
document.writeln(" </center></h3></div> "); 
document.writeln(" </form></body> "); 
document.writeln("  </html> "); 
document.writeln("  ");
 // -->
</script>